"""
Graphql Schemadefinitie voor het Leveringsregister
Versie 
datum 
Gabseerd op Leveringsregister 1
"""

schema {
  query: Query
}

"""
Custom Scalar definities
"""

"""
The `UUID` scalar represents an version 4 UUID specification
"""
scalar UUID @specifiedBy(url: "https://tools.ietf.org/html/rfc4122")

"""
The `Date` scalar represents an ISO-8601 compliant date type. YYYY-MM-DD
"""
scalar Date
  @specifiedBy(url: "https://scalars.graphql.org/andimarek/local-date")

"""
The `DateTime` scalar represents an ISO-8601 compliant date time type.
"""
scalar DateTime
  @specifiedBy(url: "https://scalars.graphql.org/andimarek/date-time")

"""
  QUERY definities
"""

type Query {
_Query: query
}
    

"""
object types
"""


"""
Filter input types
"""


input UuidOperationFilterInput {
  eq: UUID
}

input StringOperationFilterInput {
  and: [StringOperationFilterInput!]
  or: [StringOperationFilterInput!]
  eq: String
}
