# QLR-0009-ZK.graphql
# Query voor uitvoerend zorgkantoor op Leveringsregister, raadplegen status Levering informatieve bemiddelingspecificatie
# Verplichte input:
# - bemiddelingspecificatieIDInformatief

query Levering($bemiddelingspecificatieIDInformatief: UUID!) {
  levering(
    where: {
      bemiddelingspecificatieID: { eq: $bemiddelingspecificatieIDInformatief }
    }
  ) {
    leveringID
    bemiddelingspecificatieID
    client {
      clientID
      bsn
    }
    leveringperiodes {
      leveringperiodeID
      ingangsdatum
      vaststellingMoment
      sleuteldatum
      einddatum
      beeindigingReden
      aanbiederBestemming
      behandelingperiodes {
        behandelingperiodeID
        ingangsdatum
        einddatum
      }
    }
    uitstelperiodes {
      uitstelperiodeID
      ingangsdatum
      vaststellingMoment
      reden
      leveringsstatus
      leveringsstatusClassificatie
      einddatum
    }
    afstel {
      afstelID
      afsteldatum
      vaststellingMoment
      reden
      aanbiederBestemming
    }
  }
}
