# QLR-0002-ZA.graphql
# Query voor aanbieders op Leveringsregister 
# Verplichte input:
#   - verzoekAanbiederID
#   - agbcode aanbieder


Query VerzoekAanbieder(
    $verzoekAanbiederID: UUID!
    $aanbieder: String!
){
    verzoekAanbieder(
        where:{
            verzoekAanbiederID: {eq: $bemiddelingspecificatieID}
            aanbieder: {eq: $aanbieder}
        }
    ){
        verzoekAanbiederID
        aanbieder
        toewijzingIngangsdatum
        toewijzingEinddatum
        toewijzingPercentage
        opname
        regiehouder
        verzoek{
            verzoekID
            verzoekdatum
            product
            toewijzingSoort
            leveringsvorm
            volume
            eenheid
            frequentie
            doelmatig
            toeslagreden
            verantwoord
            levering{
                leveringID
                client{
                   clientID
                   bsn 
                }
            }
        }
    }
}